import express from "express";

import {
  getEmployees, // Working
  createEmployee,
  getEmployee,
  updateEmployee,
  deleteEmployee,
} from "../controllers/employeeController.js";

const router = express.Router();

router.get("/", getEmployees); // OK
router.post("/", createEmployee); // Working but EmployeeId increments even when the createEmployee fails
router.get("/:id", getEmployee);  // Accessible on parent route /api/employees/:id, although id is generated by MongoDB as of now
router.put("/:id", updateEmployee); // Working
router.delete("/:id", deleteEmployee);  // Working

export default router;
